services:
bot:
build:
context: .
dockerfile: Dockerfile
container_name: image_generator_bot
restart: unless-stopped

env_file:
  - .env

environment:
  API_URL: http://api:8000

depends_on:
  - api

mem_limit: 512m
cpus: 0.5


api:
build:
context: .
dockerfile: Dockerfile
container_name: image_generator_api
restart: unless-stopped

env_file:
  - .env

command: uvicorn Api.main:app --host 0.0.0.0 --port 8000

mem_limit: 512m
cpus: 0.5